name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
      with:
        php_extensions: sockets
    - uses: php-actions/phpunit@v3
    - run: composer exec phpunit -v -- --bootstrap vendor/autoload.php test